# Site settings
title: Tfzhang Blog    				  	#你博客的标题
SEOTitle: Tfzhang Blog   	 #显示在浏览器上搜索的时候显示的标题
#header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
header-img: img/diamond.jpg
email: tfzhang@mai.zjgsu.edu.cn	
description: "Tfzhang Blog"  			 #网站介绍
keyword: "全球某工商tfzhang的博客, linux, 编程" #关键词
url: "https://bigbug55.gitee.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
#baseurl: "/bom" # the subpath of your site, e.g. /blog      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://gitee.com/bigbug55/bigbug55" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "这个世界很大, 不只有人类社会那点事~"
sidebar-avatar: /img/tfzhang_avartar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     ckjcode
# zhihu_username:     ckjcode
# github_username:    ckjcode
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
#twitter_username:   ckjcode




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus（https://disqus.com/）
disqus_username: disqus_MYa0zLAXqu

# Gitalk
#gitalk:
#  enable: true    #是否开启Gitalk评论
#  clientID: 3bea69473b3a33474b94                            #生成的clientID
#  clientSecret: 0bc2fff2064a2e3d6fa0068641c0e31eedee6fd8    #生成的clientSecret
#  repo: ChengKeJ.github.io    #仓库名称
#  owner: ChengKeJ    #github用户名
#  admin: ChengKeJ
#  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 26e40ab3fe3239b30a24bfa32c51433b


# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: ckjcode.gitee.io               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



 #Friends
#  friends: [
#      {
#          title: "WY",
#          href: "http://zhengwuyang.com"
#      },{
#          title: "简书·BY",
#          href: "http://www.jianshu.com/u/e71990ada2fd"
#      },{
#          title: "Apple",
#          href: "https://apple.com"
#      },{
#          title: "Apple Developer",
#          href: "https://developer.apple.com/"
#      }
#  ]

theme: jekyll-theme-slate
